version: '3.8'


services:
  web:
    build: 
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    container_name: helpdesk
    command: /start
    volumes:
      - .:/app
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      - redis


  redis:
    image: redis:6-alpine


  celery_worker:
    build: 
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-celeryworker
    container_name: celery-worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      

  celery_beat:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      

  flower:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5557:5555
    depends_on:
      - redis
      
    


