#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A helpdesk inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

celery -A helpdesk  \
    --broker="redis://127.0.0.1:6379" \
    flower