# Generated by Django 4.1.3 on 2022-12-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
