# Generated by Django 4.1.3 on 2022-12-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickets_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='engmail',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='engmobileNo',
        ),
    ]
