# Generated by Django 4.1.3 on 2022-12-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_tickets_engmail_remove_tickets_engmobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
